
import '../globals.css'
import type { Metadata } from 'next'
import SearchHeader from '@/components/SearchHeader'


export const metadata: Metadata = {
  title: 'My Seach Engine',
  description: 'Google Clone App. Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div>
      <SearchHeader />
      {children}
    </div>
  )
}