import Footer from '@/components/Footer'
import './globals.css'
import type { Metadata } from 'next'


export const metadata: Metadata = {
  title: 'My Seach Engine',
  description: 'Google Clone App. Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='relative min-h-screen'>
        {children}
        {/* Footer */}
        <Footer />
      </body>
    </html>
  )
}
